// Options that describe how an entity is stored. protoc-gen-go-entity reads
// them and generates the entity's Scheme entry.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.36.2
// source: entity/options.proto

package entitypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_entity_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         50100,
		Name:          "x.entity.namespace",
		Tag:           "varint,50100,opt,name=namespace",
		Filename:      "entity/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50101,
		Name:          "x.entity.tenant",
		Tag:           "varint,50101,opt,name=tenant",
		Filename:      "entity/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50102,
		Name:          "x.entity.sensitive",
		Tag:           "varint,50102,opt,name=sensitive",
		Filename:      "entity/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: ([]uint32)(nil),
		Field:         50100,
		Name:          "x.entity.retired",
		Tag:           "varint,50100,rep,packed,name=retired",
		Filename:      "entity/options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// namespace prefixes every key of the entity. Unique across the entities of
	// one Scheme, nonzero, and never reused once data has been written under it.
	//
	// optional uint32 namespace = 50100;
	E_Namespace = &file_entity_options_proto_extTypes[0]
	// tenant scopes the entity's keys to the tenant in the context.
	//
	// optional bool tenant = 50101;
	E_Tenant = &file_entity_options_proto_extTypes[1]
	// sensitive encrypts the entity at rest.
	//
	// optional bool sensitive = 50102;
	E_Sensitive = &file_entity_options_proto_extTypes[2]
)

// Extension fields to descriptorpb.FileOptions.
var (
	// retired lists namespaces of deleted entities, which no entity may take.
	//
	// repeated uint32 retired = 50100;
	E_Retired = &file_entity_options_proto_extTypes[3]
)

var File_entity_options_proto protoreflect.FileDescriptor

const file_entity_options_proto_rawDesc = "" +
	"\n" +
	"\x14entity/options.proto\x12\bx.entity\x1a google/protobuf/descriptor.proto:?\n" +
	"\tnamespace\x12\x1f.google.protobuf.MessageOptions\x18\xb4\x87\x03 \x01(\rR\tnamespace:9\n" +
	"\x06tenant\x12\x1f.google.protobuf.MessageOptions\x18\xb5\x87\x03 \x01(\bR\x06tenant:?\n" +
	"\tsensitive\x12\x1f.google.protobuf.MessageOptions\x18\xb6\x87\x03 \x01(\bR\tsensitive:8\n" +
	"\aretired\x12\x1c.google.protobuf.FileOptions\x18\xb4\x87\x03 \x03(\rR\aretiredB%Z#github.com/iv-one/x/entity/entitypbb\x06proto3"

var file_entity_options_proto_goTypes = []any{
	(*descriptorpb.MessageOptions)(nil), // 0: google.protobuf.MessageOptions
	(*descriptorpb.FileOptions)(nil),    // 1: google.protobuf.FileOptions
}
var file_entity_options_proto_depIdxs = []int32{
	0, // 0: x.entity.namespace:extendee -> google.protobuf.MessageOptions
	0, // 1: x.entity.tenant:extendee -> google.protobuf.MessageOptions
	0, // 2: x.entity.sensitive:extendee -> google.protobuf.MessageOptions
	1, // 3: x.entity.retired:extendee -> google.protobuf.FileOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	0, // [0:4] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_options_proto_init() }
func file_entity_options_proto_init() {
	if File_entity_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entity_options_proto_rawDesc), len(file_entity_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_entity_options_proto_goTypes,
		DependencyIndexes: file_entity_options_proto_depIdxs,
		ExtensionInfos:    file_entity_options_proto_extTypes,
	}.Build()
	File_entity_options_proto = out.File
	file_entity_options_proto_goTypes = nil
	file_entity_options_proto_depIdxs = nil
}
