// The key types an entity's id field takes. Each implements entity.ID in
// ids.go, so a message whose id is one of them needs no hand-written code.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: entity/ids/ids.proto

package ids

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ID is a 12-byte xid.
type ID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []byte                 `protobuf:"bytes,1,opt,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ID) Reset() {
	*x = ID{}
	mi := &file_entity_ids_ids_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ID) ProtoMessage() {}

func (x *ID) ProtoReflect() protoreflect.Message {
	mi := &file_entity_ids_ids_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ID.ProtoReflect.Descriptor instead.
func (*ID) Descriptor() ([]byte, []int) {
	return file_entity_ids_ids_proto_rawDescGZIP(), []int{0}
}

func (x *ID) GetIds() []byte {
	if x != nil {
		return x.Ids
	}
	return nil
}

// UUID is a 16-byte UUID v4.
type UUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_entity_ids_ids_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_entity_ids_ids_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_entity_ids_ids_proto_rawDescGZIP(), []int{1}
}

func (x *UUID) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

// TenantID is a 4-byte little-endian uint32, the prefix of every tenant-scoped
// key.
type TenantID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tid           []byte                 `protobuf:"bytes,1,opt,name=tid,proto3" json:"tid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantID) Reset() {
	*x = TenantID{}
	mi := &file_entity_ids_ids_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantID) ProtoMessage() {}

func (x *TenantID) ProtoReflect() protoreflect.Message {
	mi := &file_entity_ids_ids_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantID.ProtoReflect.Descriptor instead.
func (*TenantID) Descriptor() ([]byte, []int) {
	return file_entity_ids_ids_proto_rawDescGZIP(), []int{2}
}

func (x *TenantID) GetTid() []byte {
	if x != nil {
		return x.Tid
	}
	return nil
}

// SID is a string id.
type SID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           string                 `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SID) Reset() {
	*x = SID{}
	mi := &file_entity_ids_ids_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SID) ProtoMessage() {}

func (x *SID) ProtoReflect() protoreflect.Message {
	mi := &file_entity_ids_ids_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SID.ProtoReflect.Descriptor instead.
func (*SID) Descriptor() ([]byte, []int) {
	return file_entity_ids_ids_proto_rawDescGZIP(), []int{3}
}

func (x *SID) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

// EmailID is an email address, lowercased and trimmed.
type EmailID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailID) Reset() {
	*x = EmailID{}
	mi := &file_entity_ids_ids_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailID) ProtoMessage() {}

func (x *EmailID) ProtoReflect() protoreflect.Message {
	mi := &file_entity_ids_ids_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailID.ProtoReflect.Descriptor instead.
func (*EmailID) Descriptor() ([]byte, []int) {
	return file_entity_ids_ids_proto_rawDescGZIP(), []int{4}
}

func (x *EmailID) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// TokenID is random bytes, written as base64url.
type TokenID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         []byte                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenID) Reset() {
	*x = TokenID{}
	mi := &file_entity_ids_ids_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenID) ProtoMessage() {}

func (x *TokenID) ProtoReflect() protoreflect.Message {
	mi := &file_entity_ids_ids_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenID.ProtoReflect.Descriptor instead.
func (*TokenID) Descriptor() ([]byte, []int) {
	return file_entity_ids_ids_proto_rawDescGZIP(), []int{5}
}

func (x *TokenID) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

// Rel is the composite key of a relation between two entities.
type Rel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *ID                    `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *ID                    `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rel) Reset() {
	*x = Rel{}
	mi := &file_entity_ids_ids_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rel) ProtoMessage() {}

func (x *Rel) ProtoReflect() protoreflect.Message {
	mi := &file_entity_ids_ids_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rel.ProtoReflect.Descriptor instead.
func (*Rel) Descriptor() ([]byte, []int) {
	return file_entity_ids_ids_proto_rawDescGZIP(), []int{6}
}

func (x *Rel) GetFrom() *ID {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Rel) GetTo() *ID {
	if x != nil {
		return x.To
	}
	return nil
}

// NilID is the empty id of a singleton.
type NilID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idx           int32                  `protobuf:"varint,1,opt,name=idx,proto3" json:"idx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NilID) Reset() {
	*x = NilID{}
	mi := &file_entity_ids_ids_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NilID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NilID) ProtoMessage() {}

func (x *NilID) ProtoReflect() protoreflect.Message {
	mi := &file_entity_ids_ids_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NilID.ProtoReflect.Descriptor instead.
func (*NilID) Descriptor() ([]byte, []int) {
	return file_entity_ids_ids_proto_rawDescGZIP(), []int{7}
}

func (x *NilID) GetIdx() int32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

var File_entity_ids_ids_proto protoreflect.FileDescriptor

const file_entity_ids_ids_proto_rawDesc = "" +
	"\n" +
	"\x14entity/ids/ids.proto\x12\fx.entity.ids\"\x16\n" +
	"\x02ID\x12\x10\n" +
	"\x03ids\x18\x01 \x01(\fR\x03ids\"\x1a\n" +
	"\x04UUID\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\"\x1c\n" +
	"\bTenantID\x12\x10\n" +
	"\x03tid\x18\x01 \x01(\fR\x03tid\"\x17\n" +
	"\x03SID\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\tR\x03sid\"\x1f\n" +
	"\aEmailID\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\x1f\n" +
	"\aTokenID\x12\x14\n" +
	"\x05token\x18\x01 \x01(\fR\x05token\"M\n" +
	"\x03Rel\x12$\n" +
	"\x04from\x18\x01 \x01(\v2\x10.x.entity.ids.IDR\x04from\x12 \n" +
	"\x02to\x18\x02 \x01(\v2\x10.x.entity.ids.IDR\x02to\"\x19\n" +
	"\x05NilID\x12\x10\n" +
	"\x03idx\x18\x01 \x01(\x05R\x03idxB Z\x1egithub.com/iv-one/x/entity/idsb\x06proto3"

var (
	file_entity_ids_ids_proto_rawDescOnce sync.Once
	file_entity_ids_ids_proto_rawDescData []byte
)

func file_entity_ids_ids_proto_rawDescGZIP() []byte {
	file_entity_ids_ids_proto_rawDescOnce.Do(func() {
		file_entity_ids_ids_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entity_ids_ids_proto_rawDesc), len(file_entity_ids_ids_proto_rawDesc)))
	})
	return file_entity_ids_ids_proto_rawDescData
}

var file_entity_ids_ids_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_entity_ids_ids_proto_goTypes = []any{
	(*ID)(nil),       // 0: x.entity.ids.ID
	(*UUID)(nil),     // 1: x.entity.ids.UUID
	(*TenantID)(nil), // 2: x.entity.ids.TenantID
	(*SID)(nil),      // 3: x.entity.ids.SID
	(*EmailID)(nil),  // 4: x.entity.ids.EmailID
	(*TokenID)(nil),  // 5: x.entity.ids.TokenID
	(*Rel)(nil),      // 6: x.entity.ids.Rel
	(*NilID)(nil),    // 7: x.entity.ids.NilID
}
var file_entity_ids_ids_proto_depIdxs = []int32{
	0, // 0: x.entity.ids.Rel.from:type_name -> x.entity.ids.ID
	0, // 1: x.entity.ids.Rel.to:type_name -> x.entity.ids.ID
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_entity_ids_ids_proto_init() }
func file_entity_ids_ids_proto_init() {
	if File_entity_ids_ids_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entity_ids_ids_proto_rawDesc), len(file_entity_ids_ids_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_ids_ids_proto_goTypes,
		DependencyIndexes: file_entity_ids_ids_proto_depIdxs,
		MessageInfos:      file_entity_ids_ids_proto_msgTypes,
	}.Build()
	File_entity_ids_ids_proto = out.File
	file_entity_ids_ids_proto_goTypes = nil
	file_entity_ids_ids_proto_depIdxs = nil
}
